### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by eamena-github** [azerbini/eamena_v3#42]
When searching for 'pottery neolithic' search results are returned that are contain the generic 'neolithic' rather than only specifically Pottery Neolithic sites. Screenshot attached.

Search:
![screen shot 2017-10-13 at 15 50 42](https://user-images.githubusercontent.com/32707884/31552139-7e704e1e-b02e-11e7-86fe-f3622724c970.png)

One of the results:
![screen shot 2017-10-13 at 15 52 40](https://user-images.githubusercontent.com/32707884/31552181-9d59fd7a-b02e-11e7-86f3-66367aed9b19.png)

**Comment by azerbini** [comment]
Beginning wildcard needs to be included in Search logic, as per requirements.

**Comment by ahaith** [comment]
We did enable the 'fuzzy' matching, so that a search for e.g. "Roman" returns "Early Roman", "Late Roman" etc.

I think the issue here is that the string term "pottery neolithic" was searching for "pottery" OR "neolithic".

I've just pushed a commit to azerbini/advanced-search which makes this an AND, which worked for a similar case for me with "late roman" as the search term.

**Comment by azerbini** [comment]
@ahaith excellent, meets requirements
