### ISSUE TITLE
Searching for parent or child E27 records

### ISSUE THREAD

**Issue by MattHobson** [azerbini/eamena_v3#44]
A search based on the name of a E27 ‘parent’ record does not find attributes of the E27 ‘child’ records. E.g. a search for name ‘Bulla Regia’ + Feature evidence interpretation type ‘theatre’ does not find the theatre of Bulla Regia.

**Comment by azerbini** [comment]
@MattHobson looks to be working to me, since the search below correctly pulls out the E27 for Bulla Regia, which indeed contains Theatre as a Feature Interpretation.

I guess what you mean is something else, @MattHobson. You want to be able to pull out the related resources of the parent Bulla Regia record (see #20). This is one of two features still 'in design'. Early next week, the interface will change, and you will be able to click a toggle button that, instead of returning Bulla Regia, will return its related resources. Then you can perform further refinements of that list by, for example, searching by Feature Interpretation for 'Theatre'. This will correctly pull out your Bulla Regia theatre.

![screen shot 2017-10-13 at 16 43 04](https://user-images.githubusercontent.com/19243127/31554471-9a476bc0-b035-11e7-9bf5-9219cea5dd64.png)

**Comment by MattHobson** [comment]
Sounds good ☺

Dr. Matthew S. Hobson
CPF-EAMENA Training Manager (North Africa)
School of Archaeology and Ancient History
University of Leicester
Project: Training in endangered archaeology methodology with Middle East and North African heritage stakeholders
OFFICE TEL: 0044 (0) 116 3736248

**Comment by azerbini** [comment]
@ahaith & @markdoub  See the above for a perfect use case of why we need the enhancement ticketed in #20

**Comment by azerbini** [comment]
Commits in #15 address this
